# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/rojo_/COMPE475_Project/Constraint_files/Basys-3-Master.xdc

# Block Designs: bd/MB1/MB1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1 || ORIG_REF_NAME==MB1} -quiet] -quiet

# IP: bd/MB1/ip/MB1_clk_wiz_0_1/MB1_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_clk_wiz_0_1 || ORIG_REF_NAME==MB1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/MB1/ip/MB1_microblaze_0_0/MB1_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_microblaze_0_0 || ORIG_REF_NAME==MB1_microblaze_0_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_dlmb_v10_0/MB1_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_dlmb_v10_0 || ORIG_REF_NAME==MB1_dlmb_v10_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_ilmb_v10_0/MB1_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_ilmb_v10_0 || ORIG_REF_NAME==MB1_ilmb_v10_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_dlmb_bram_if_cntlr_0/MB1_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB1_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_ilmb_bram_if_cntlr_0/MB1_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB1_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_lmb_bram_0/MB1_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_lmb_bram_0 || ORIG_REF_NAME==MB1_lmb_bram_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_mdm_1_0/MB1_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_mdm_1_0 || ORIG_REF_NAME==MB1_mdm_1_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_rst_clk_wiz_0_100M_0/MB1_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==MB1_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_axi_uartlite_0_0/MB1_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_axi_uartlite_0_0 || ORIG_REF_NAME==MB1_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_microblaze_0_axi_periph_0/MB1_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB1_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_axi_gpio_0_0/MB1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_axi_gpio_0_0 || ORIG_REF_NAME==MB1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/MB1/ip/MB1_axi_gpio_0_1/MB1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_axi_gpio_0_1 || ORIG_REF_NAME==MB1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/MB1/ip/MB1_xbar_0/MB1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==MB1_xbar_0 || ORIG_REF_NAME==MB1_xbar_0} -quiet] -quiet

# XDC: c:/Users/rojo_/COMPE475_Project/project_1_2023.2/project_1_2023.2.gen/sources_1/bd/MB1/MB1_ooc.xdc
