# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/rojo_/COMPE475_Project/project_1_2023.2/project_1_2023.2.srcs/sources_1/bd/MB1/ip/MB1_lmb_bram_0/MB1_lmb_bram_0.xci
# IP: The module: 'MB1_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rojo_/COMPE475_Project/project_1_2023.2/project_1_2023.2.gen/sources_1/bd/MB1/ip/MB1_lmb_bram_0/MB1_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB1_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/rojo_/COMPE475_Project/project_1_2023.2/project_1_2023.2.srcs/sources_1/bd/MB1/ip/MB1_lmb_bram_0/MB1_lmb_bram_0.xci
# IP: The module: 'MB1_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rojo_/COMPE475_Project/project_1_2023.2/project_1_2023.2.gen/sources_1/bd/MB1/ip/MB1_lmb_bram_0/MB1_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB1_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
